name: trigger gitlab job
on:
    workflow_dispatch:
jobs:
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      uses: appleboy/gitlab-ci-action@v1.3.0
      id: trigger
      with:
        host: "https://gitlab.sr-system.de/"
        token: 
        project_id: 1023
        ref: v1.0.0
        wait: true
        interval: 1s
    - name: print output
      run: |
        echo ${{ steps.trigger.outputs.id }}
        echo ${{ steps.trigger.outputs.sha }}
        echo ${{ steps.trigger.outputs.web_url }}
        echo ${{ steps.trigger.outputs.status }}
