name: Mirror to GitLab

on:
  push:
    branches:
      - '**'
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        run: |
          git remote add gitlab "https://oauth2:glpat-vSnhzvQVSbGB4g4ayhq8@gitlab.com/gurkansevinc/spryker_mirror.git"
          git push --mirror gitlab
